CC = g++
TARGET = hdt
SOURCES = CommonDef.h\
	  GeneratorC.cpp\
	  GeneratorC.h\
	  HidatoMain.cpp\
	  HidatoMain.h\
 	  Solver.cpp\
	  Solver.h

all:
	$(CC) -o $(TARGET) $(SOURCES)

clean:
	rm -rf *.o $(TARGET)